name: hotels_egypt_project
version: '1.0'
config-version: 2
profile: hotels_egypt_profile

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

models:
  hotels_egypt_project:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
